version: 2

test: &test
  steps:
    - checkout
    - run:
        name: Run lint
        command: |
          go get -u golang.org/x/lint/golint
          golint -set_exit_status
    - run:
        name: Run megacheck
        command: |
          go get -u honnef.co/go/tools/cmd/megacheck
          megacheck -simple.exit-non-zero
    - run:
        name: Run tests
        command: go test -v

jobs:
  go-1.9-test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/y-yagi/debuglog
    <<: *test

  go-1.10-test:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/y-yagi/debuglog
    <<: *test

  go-1.11-test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/y-yagi/debuglog
    <<: *test

workflows:
  version: 2
  build:
    jobs:
      - go-1.9-test
      - go-1.10-test
      - go-1.11-test
